const listOfAnimals = [
  { animal: "pes", type: "m" },
  { animal: "kočka", type: "ž" },
  { animal: "králík", type: "s" },
  { animal: "panda", type: "m" },
  { animal: "lev", type: "m" },
  { animal: "tygr", type: "m" },
  { animal: "slon", type: "m" },
  { animal: "žirafa", type: "ž" },
  { animal: "klokan", type: "s" },
  { animal: "tukan", type: "m" },
  { animal: "orangutan", type: "m" },
  { animal: "delfín", type: "s" },
  { animal: "velryba", type: "s" },
  { animal: "plameňák", type: "m" },
  { animal: "pingvin", type: "s" },
  { animal: "krokodýl", type: "m" },
  { animal: "ježek", type: "m" },
  { animal: "víla", type: "ž" },
  { animal: "had", type: "m" },
  { animal: "leguán", type: "m" },
  { animal: "pštros", type: "m" },
  { animal: "klokan", type: "s" },
  { animal: "medvěd", type: "m" },
  { animal: "pavouk", type: "m" },
  { animal: "rys", type: "m" },
  { animal: "hroch", type: "m" },
  { animal: "nosorožec", type: "m" },
  { animal: "želva", type: "ž" },
  { animal: "koza", type: "ž" },
  { animal: "ovce", type: "ž" },
  { animal: "pštros", type: "m" },
  { animal: "alpaka", type: "s" },
  { animal: "lama", type: "ž" },
  { animal: "slepice", type: "ž" },
  { animal: "kohout", type: "m" },
  { animal: "lenochod", type: "m" },
  { animal: "ropucha", type: "ž" },
  { animal: "netopýr", type: "m" },
  { animal: "rak", type: "m" },
  { animal: "mravenec", type: "m" },
  { animal: "pavouk", type: "m" },
  { animal: "žába", type: "ž" },
  { animal: "andulka", type: "ž" },
  { animal: "holub", type: "m" },
  { animal: "jezevec", type: "m" },
  { animal: "lenochod", type: "m" },
  { animal: "včela", type: "ž" },
  { animal: "motýl", type: "m" },
  { animal: "ještěrka", type: "ž" },
  { animal: "los", type: "m" },
  { animal: "lachtan", type: "m" },
  { animal: "surikata", type: "ž" },
  { animal: "orangutan", type: "m" },
  { animal: "sob", type: "m" },
  { animal: "klokan", type: "s" },
  { animal: "krab", type: "m" },
  { animal: "krtek", type: "m" },
  { animal: "krokodýl", type: "m" },
  { animal: "slepice", type: "ž" },
  { animal: "holub", type: "m" },
  { animal: "lemur", type: "m" },
  { animal: "mlok", type: "m" },
  { animal: "šneček", type: "m" },
  { animal: "želva", type: "ž" },
  { animal: "kráva", type: "ž" },
  { animal: "tučňák", type: "m" },
  { animal: "lama", type: "ž" },
  { animal: "sova", type: "ž" },
  { animal: "krab", type: "m" },
  { animal: "včela", type: "ž" },
  { animal: "los", type: "m" },
  { animal: "lenochod", type: "m" },
  { animal: "netopýr", type: "m" },
  { animal: "kůň", type: "m" },
  { animal: "koza", type: "ž" },
  { animal: "žirafa", type: "ž" },
  { animal: "tuleň", type: "m" },
  { animal: "aligátor", type: "m" },
  { animal: "mrož", type: "m" },
  { animal: "pštros", type: "m" },
  { animal: "pavouk", type: "m" },
  { animal: "lenochod", type: "m" },
  { animal: "rak", type: "m" },
  { animal: "ježek", type: "m" },
  { animal: "žába", type: "ž" },
  { animal: "mravenec", type: "m" },
  { animal: "pavouk", type: "m" },
  { animal: "netopýr", type: "m" },
  { animal: "ještěrka", type: "ž" },
  { animal: "medvěd", type: "m" },
  { animal: "sob", type: "m" },
  { animal: "krab", type: "m" },
  { animal: "krtek", type: "m" },
  { animal: "klokan", type: "s" },
  { animal: "slepice", type: "ž" },
  { animal: "hroch", type: "m" },
  { animal: "velryba", type: "s" },
  { animal: "aligátor", type: "m" },
  { animal: "želva", type: "ž" },
  { animal: "kráva", type: "ž" },
];

const listOfAdjectives = [
  "ulekaná",
  "huňatá",
  "veselá",
  "smutná",
  "hravá",
  "divoká",
  "domácí",
  "exotická",
  "roztomilá",
  "ostražitá",
  "plachá",
  "agresivní",
  "klidná",
  "energická",
  "lenivá",
  "rychlá",
  "pomalá",
  "silná",
  "slabá",
  "mladá",
  "stará",
  "velká",
  "malá",
  "štíhlá",
  "tlustá",
  "elegantní",
  "neohrabaná",
  "šikovná",
  "nemotorná",
  "hezká",
  "ošklivá",
  "chytřá",
  "hloupá",
  "dobrá",
  "zlá",
  "štědrá",
  "sobecká",
  "společenská",
  "osamělá",
  "odvážná",
  "zbabělá",
  "milá",
  "nepříjemná",
  "přátelská",
  "nepřátelská",
  "věrná",
  "nevěrná",
  "poslušná",
  "neposlušná",
  "čistá",
  "špinavá",
  "zdravá",
  "nemocná",
  "hlasitá",
  "tichá",
  "aktivní",
  "pasivní",
  "radostná",
  "zklamaná",
  "nadšená",
  "rozčílená",
  "spokojená",
  "nespokojená",
  "pyšná",
  "skromná",
  "sebevědomá",
  "nesmělá",
  "trpělivá",
  "netrpělivá",
  "odpovědná",
  "neodpovědná",
  "upřímná",
  "lživá",
  "tolerantní",
  "netolerantní",
  "optimistická",
  "pesimistická",
  "ambiciózní",
  "pohodlná",
  "snaživá",
  "líná",
  "kreativní",
  "nekreativní",
  "inteligentní",
  "neinteligentní",
  "vzdělaná",
  "nevzdělaná",
  "bohatá",
  "chudá",
  "štěstlivá",
  "neštěstlivá",
  "svobodná",
  "zajatá",
  "bezpečná",
  "ohrožená",
  "živá",
  "mrtvá",
  "divoká",
  "domestikovaná",
  "plodná",
  "neplodná",
  "mladistvá",
  "starobylá",
  "moderní",
  "staromódní",
  "barevná",
  "bezbarvá",
  "jasná",
  "tmavá",
  "lehká",
  "těžká",
  "měkká",
  "tvrdá",
  "teplá",
  "studená",
  "mokrá",
  "suchá",
  "hladová",
  "syta",
  "žíznivá",
  "nasytěná",
  "spící",
  "bdělá",
  "klidná",
  "rozrušená",
  "spokojená",
  "frustrovaná",
  "zvědavá",
  "lhostejná",
  "šťastná",
  "smutná",
  "zamilovaná",
  "rozčílená",
  "nadšená",
  "zklamaná",
  "překvapená",
  "vystrašená",
  "zmatená",
  "odhodlaná",
  "bezmocná",
  "nadějná",
  "beznadějná",
  "zoufalá",
  "vzrušená",
  "nudná",
  "znechucená",
  "odpudivá",
  "přitažlivá",
  "odporná",
  "oblíbená",
  "neoblíbená",
  "obyčejná",
  "neobyčejná",
  "obydlená",
  "neobydlená",
  "oživená",
  "mrtvá",
  "přirozená",
  "umělá",
  "krásná",
  "ošklivá",
  "příjemná",
  "nepříjemná",
  "přátelská",
  "nepřátelská",
  "milá",
  "nemilá",
  "sladká",
  "hořká",
  "kyselá",
  "slaná",
  "ostrá",
  "měkká",
  "tvrdá",
  "lehká",
  "těžká",
  "teplá",
  "studená",
  "mokrá",
  "suchá",
  "hladová",
  "syta",
  "žíznivá",
  "nasytěná",
  "spící",
  "bdělá",
  "klidná",
  "rozrušená",
  "spokojená",
  "frustrovaná",
  "zvědavá",
  "lhostejná",
  "šťastná",
  "smutná",
  "zamilovaná",
  "rozčílená",
  "nadšená",
  "zklamaná",
  "překvapená",
  "vystrašená",
  "zmatená",
  "odhodlaná",
  "bezmocná",
  "nadějná",
  "beznadějná",
  "zoufalá",
  "vzrušená",
  "nudná",
  "znechucená",
  "odpudivá",
  "přitažlivá",
  "odporná",
  "oblíbená",
  "neoblíbená",
  "obyčejná",
  "neobyčejná",
  "obydlená",
  "neobydlená",
  "oživená",
  "mrtvá",
  "přirozená",
  "umělá",
  "krásná",
  "ošklivá",
  "příjemná",
  "nepříjemná",
  "přátelská",
  "nepřátelská",
  "milá",
  "nemilá",
  "sladká",
  "hořká",
  "kyselá",
  "slaná",
  "ostrá",
  "měkká",
  "tvrdá",
  "lehká",
  "těžká",
  "teplá",
  "studená",
  "mokrá",
  "suchá",
  "hladová",
  "syta",
  "žíznivá",
  "nasytěná",
  "spící",
  "bdělá",
  "klidná",
  "rozrušená",
  "spokojená",
  "frustrovaná",
  "zvědavá",
  "lhostejná",
  "šťastná",
  "smutná",
  "zamilovaná",
  "rozčílená",
  "nadšená",
  "zklamaná",
  "překvapená",
  "vystrašená",
  "zmatená",
  "odhodlaná",
  "bezmocná",
  "nadějná",
  "beznadějná",
  "zoufalá",
  "vzrušená",
  "nudná",
  "znechucená",
  "odpudivá",
  "přitažlivá",
];

export const generateRandomNickname = (): string => {
  const randomAdj =
    listOfAdjectives[Math.floor(Math.random() * listOfAdjectives.length)];
  const randomAnimal =
    listOfAnimals[Math.floor(Math.random() * listOfAnimals.length)];

  if (randomAnimal.type === "m") {
    //replace the last character with "ý" in randomAdj
    const adj = randomAdj.slice(0, -1);
    return `${adj}ý ${randomAnimal.animal}`;
  }
  if (randomAnimal.type === "ž") {
    //replace the last character with "á" in randomAdj
    const adj = randomAdj.slice(0, -1);
    return `${adj}á ${randomAnimal.animal}`;
  }
  if (randomAnimal.type === "s") {
    //replace the last character with "é" in randomAdj
    const adj = randomAdj.slice(0, -1);
    return `${adj}é ${randomAnimal.animal}`;
  }

  return `${randomAdj} ${randomAnimal.animal}`;
};
