export const SecurityQuestions = [
  "Jaké je vaše rodné příjmení?",
  "Kde jste se narodili?",
  "Jaké je vaše oblíbené jídlo?",
  "Kolik máte sourozenců?",
  "Jaké je vaše nejoblíbenější barva?",
  "Jaké je vaše nejoblíbenější zvíře?",
  "Kdo je vaším nejlepším přítelem?",
  "Jaké je vaše nejoblíbenější sportovní družstvo?",
  "Kde jste strávili své dětství?",
  "Jaké je vaše nejoblíbenější kniha?",
  "Kolik máte dětí?",
  "Jaké je vaše nejoblíbenější filmové žánr?",
  "Kdo je vaším oblíbeným hercem/herečkou?",
  "Jaké je vaše nejoblíbenější hudební žánr?",
  "Kde jste se poprvé setkali se svým partnerem/partnerkou?",
  "Jaké je vaše nejoblíbenější cestovní místo?",
  "Kolik máte vysokoškolských titulů?",
  "Jaké je vaše nejoblíbenější roční období?",
  "Kdo je vaším nejoblíbenějším umělcem?",
  "Jaké je vaše nejoblíbenější sportovní událost?",
  "Kde jste se naučili řídit auto?",
  "Jaké je vaše nejoblíbenější restaurace?",
  "Kolik máte domácích mazlíčků?",
  "Jaké je vaše nejoblíbenější televizní pořad?",
  "Kdo je vaším nejoblíbenějším spisovatelem/spisovatelkou?",
  "Jaké je vaše nejoblíbenější památkové místo?",
  "Kde jste strávili svou poslední dovolenou?",
  "Jaké je vaše nejoblíbenější sportovní aktivita?",
  "Kolik máte sourozenců?",
  "Jaké je vaše nejoblíbenější značka oblečení?",
  "Kdo je vaším nejoblíbenějším hudebním interpretem?",
  "Jaké je vaše nejoblíbenější jídlo?",
  "Kde jste se setkali se svým nejlepším přítelem?",
  "Jaké je vaše nejoblíbenější hobby?",
  "Kolik máte tetiček a strýčků?",
  "Jaké je vaše nejoblíbenější sportovní tým?",
  "Kdo je vaším nejoblíbenějším politikem/političkou?",
  "Jaké je vaše nejoblíbenější rostlina?",
  "Kde jste se naučili plavat?",
  "Jaké je vaše nejoblíbenější město?",
  "Kolik máte prarodičů?",
  "Jaké je vaše nejoblíbenější hra?",
  "Kdo je vaším nejoblíbenějším historickou postavou?",
];
